### ISSUE TITLE
Event Types

### ISSUE THREAD

**Issue by gmeade** [kingjr/meg_expectation_p3#1]
Hi -

Believe it or not, I fixed the export path issue and have the whole pipeline working on my computer! So now I'm moving to defining the other contrasts... I'm confused about which event codes correspond to what. I'm assuming that I can just use the ttl values for the stim events, right? Do you know offhand what the motor response event codes are? And the syntax for combining multiple values (either consecutive or not) or, for example, a stim code and a motor code?

Thanks!
G

**Comment by gmeade** [comment]
Also - if you're still keeping track of how to set things up on a Mac, this is what I did: http://apple.stackexchange.com/questions/99835/how-to-create-bash-profile-and-profile

**Comment by kingjr** [comment]
Great! Can you update the README file so that we keep a trace of what should be done in case we want to install the scripts on another computer ?

Regarding the TTL: yes the stims are coded in the TTL (in our case, the channel should be 101). values strictly below 8192 code for stimulus trigger, while 8192 and above code for the response buttons.

To get the syntax / correspondance you can either do it manually by checking matlab trials(ii).ttl.value with the corresponding conditions or, there is a 'ttl' folder in jr_toolbox that allows you to map and read ttl values directly. I don't have matlab right now, so I'll make you an example tomorrow.

**Comment by gmeade** [comment]
Yep, I can update the README file with what I know, but you kept notes of what we did yesterday, right?

Just so you know for tomorrow, I already have the corresponding ttl values for each of the stim conditions, but it was the response buttons I didn't know (e.g., right_green = what event code?) because they are coded in words in the behavioral structure that I've been using until now and we didn't save the response trigger code values themselves anywhere. Also, FYI, I just found out that one of the contrasts that you listed in the scripts (top/bottom) isn't coded directly in the triggers... I hadn't thought of that contrast when you asked me if everything was coded in the triggers since we have never done anything with that (except decoding, which we used the behavioral trial structure for - it is coded there).

One final question (that you can also save for tomorrow) - I know from experience that the behavioral trial structure and triggers extracted from the M/EEG data structure often don't match up - there are often missing or additional triggers. How does that work if we just consider the triggers? Won't the extra triggers make us include epochs that we shouldn't be including?

**Comment by kingjr** [comment]
Yes, we can try to check the correspondance. Especially as the top versus bottom is a good contrast for sanity checks.

If you go in my perceptual decision repository, you can get an example on how to do this. But it s not urgent so it s probably better to do this once you're in Paris.

**Comment by gmeade** [comment]
I think I still need a more concrete example in order to define these contrasts. So, for example for the letter/number contrast, the triggers 5 7 17-20 29-32 41-44 54 56 all correspond to letter trials (i.e., multiples of 12 + 5 : multiples of twelve + 8). But how do I write that out nicely?

if event['type'] == 'stim':
if events[ii,2] == all of the above : <-- here, do I just have a vector with all of the corresponding trigger values or is there a more elegant way to includes all of the values?
event['target'] = 'letter'
if events[ii,2] == number triggers
event['target'] = 'number'
if events[ii,2] == absent triggers
event['target'] == 'absent'

And then for the other contrasts that depend on both stim triggers and responses (e.g., accuracy):

if event['type'] == 'stim_motor':
if events[ii,2] == same as above (or is there a way to use the fact that I already defined event['target'] above?) & events[ii+1,2] == the correct response:
event['accuracy'] = 'correct'
else: event['accuracy']='incorrect'

And, finally, the order for each trial is target, objective accuracy, PAS rating, right? There are no triggers for the mask or other events?

Sorry if these are obnoxious questions. I feel like these are things I should be able to figure out on my own, but I am completely lost now!

**Comment by gmeade** [comment]
Also, I'm still waiting for the response codes from you, right?

**Comment by kingjr** [comment]
To get the trigger correspondance you can go on matlab

```
addpath('/path/to/JR_toolbox/ttl/')

load('path/to/the/file/generated/during/the/experiment/73543060516_melanie_main_finished.mat', 'cfg')

% define here all triggers 
triggers = [1:12 14 32 64];
% check the value for each trigger
for t = triggers
    ttl2name(t, cfg.ttl)
end
```

**Comment by kingjr** [comment]
In python, to check multiple values you can do

```
if events[ii,2] in [1, 2, 3, 64]:
    print('foo')
else:
    print('bar')
```

**Comment by kingjr** [comment]
to have multiple condition you can indeed do

```
if (event['target'] == 1 and event['present']):
    print('foo')
```

**Comment by kingjr** [comment]
Regarding the order, I think there's only a trigger for the stim, but you'd need to check that from the experiment script. You can get it by loading any behavioral file in cfg.scripts you get all the script.

In our case it seems to be 
target + photo_diod + TTL on
target + photo_diod + TTL off
soa
mask on 
mask off
forced choice response
visibility response
feedback if block ends.

**Comment by gmeade** [comment]
Thanks! This is good to have, but it only gives me the stim values defined in the behavioral structure (which I have already figured out), what I am missing is the response codes (i.e., the triggers that correspond to right_green, left_green, etc.) since these are just in words in the behavioral structure. They should be generic across all experiments at NS, right? I think the rest answers the questions that I had.

**Comment by kingjr** [comment]
Mmh, it's a shame we didn't keep the binary codes too. My bad.

Note that all key triggers are high as compared to stimulus triggers. To get the correspondence, I would thus take the first subject and match these high triggers to the first trials until getting confident about which key corresponds to which code.

**Comment by gmeade** [comment]
Okay, I can do that!
