### ISSUE TITLE
Pushing

### ISSUE THREAD

**Issue by gmeade** [kingjr/meg_expectation_p3#2]
So I have defined all the contrasts and went to "push" them back onto github to get your feedback, but I get the following error message. It makes it sound like I didn't have the most recent version before I started making edits, but that can't be true because you haven't changed anything and before I started, I made sure to "pull" the latest version and it told me that I already had the latest version.

I'm wondering if it is because I worked for a bit a couple of days ago and saved without committing or pushing or maybe I'm just calling it wrong?

![screen shot 2015-03-31 at 13 48 00](https://cloud.githubusercontent.com/assets/11678885/6918265/95624904-d7ac-11e4-9aba-3fd9a9545556.png)

**Comment by kingjr** [comment]
(to copy code and prefer using three ' )

Mmmh that's a bit weird. Have you pushed from different computers?

Can you pull first and push your commits then?

**Comment by gmeade** [comment]
No, I haven't done anything on any other computer...

This is what it tells me if I try to pull. Shall I do the merge?

![screen shot 2015-03-31 at 15 27 07](https://cloud.githubusercontent.com/assets/11678885/6919836/9adc4886-d7ba-11e4-9b34-4ec23da2f9f5.png)

**Comment by kingjr** [comment]
copy and paste the files you modified elsewhere just in case, and then merge.
