### ISSUE TITLE
Defining conditions

### ISSUE THREAD

**Issue by gmeade** [kingjr/meg_expectation_p3#3]
Worked! I will get the hang of this eventually - I thought it would let me comment the changes that I made when I pushed, but I realized that that was supposed to be what I did when I committed. Oh well, I will comment them here:

1) I defined the rest of the conditions, leaving the actual triggers that need to be captured in comments just to be sure. It runs, which is a good first step, but I am trying to find a way that I double check by getting the number of events that are defined in each condition?

2) It is unhappy in later stages about the definition of PAS, but I don't really understand why it is having trouble since there should be a PAS response 2 events after every stim event. Maybe I am defining it incorrectly?

![screen shot 2015-03-31 at 13 15 22](https://cloud.githubusercontent.com/assets/11678885/6920377/36e57b5a-d7be-11e4-9a20-4bee0330bc69.png)

3) I changed your definition of stim/motor events since the smallest motor event is 64.

4) Did you know that when you defined the "motor_side" variable, it really was just the index vs. middle finger on the right hand? The 2AFC response is always with the right hand and the PAS always with the left hand. I renamed the variables so that they made more sense to me, because "motor_side" sounds like it should be left hand vs. right hand.

5) As you will see I commented out the definition of local context, because I'm a bit perplexed. The idea is to access the PAS ratings of the N-2 and N-1 trial and to categorize based on those (UU,US,SU,SS) as in the behavioral figure. So, in terms of events, it should be the N-1 and N-4 events that count. But I don't want to define it like that because, for example, at the beginning of blocks, the subjects press the buttons to advance and then the N-1 and N-4 events are no longer the ones we need.

6) Are there other missing conditions you can think of? I think I have defined all of the basic ones, but I'm a bit confused about whether this is where we define all of the contrasts that we want to look at (e.g., seen vs. unseen at middle SOAs, which includes both the PAS and SOA variables) or just make sense of all the trigger values (i.e., translate them into conditions) to later combine them.

**Comment by kingjr** [comment]
1) you can count the triggers like this
print(sum(triggers==value))

2) Mmmh, I can see how that's not really robust, but let's see. Are you extracting all events (stim and response ?) or are you filtering the response events out?

3) ok

4) Yes, I figured that out when I looked at the decoding of motor response (which was sig but not high): we can decode finger movements!

5) issue related to 2

6) we need to have each experimental condition (not the combinations of) defined in events.

**Comment by gmeade** [comment]
I don’t know? I still don’t have the big picture of how this is all working. It looks like the variable condition can be stim, motor, or both and is defined when you call the function events_select_condition in run_extract_epochs. The second argument, which corresponds to condition, is ep['events’], but I don’t see what that then corresponds to?

**Comment by kingjr** [comment]
push your code I'll try to see what I can do

**Comment by gmeade** [comment]
I haven’t changed anything since I pushed it to git hub a while ago, so you can just take what is there.

**Comment by kingjr** [comment]
Ok. I won't be working on it before a couple of hours, so you can make modifications before then

**Comment by gmeade** [comment]
Alrighty. I don’t have anything else specifically to do, but if I make any changes I will push them and let you know!

**Comment by kingjr** [comment]
Try to change run_extract_events so that it only takes events[:,2] < 64, and plot the butterfly of two categories (e;g. letters and digits)

see http://martinos.org/mne/dev/auto_examples/plot_read_epochs.html#example-plot-read-epochs-py for an example.

To make a contrast, do

```
evoked_diff = evoked1 - evoked2
evoked_dif.plot()
```

**Comment by gmeade** [comment]
Hmm… Do you mean in run_extract_epochs? I don’t see anyway to define limits on the triggers that you want to include in mne.find_events… But if you change line 83 of extract_epochs to be sel = events_select_condition(events[:,2], 'stim’), I think in theory that should work (because if condition == ‘stim’ it only takes events <= 60).

In the conditions script, am I supposed to put events_data_frame.append(event) after defining each condition or only have it at the end?

As for plotting, I can’t figure out how to define sel to just be letter or just be number, which is what I need to do in order to average them separately using mne.Epochs, right?

If you don’t mind, I think the best thing is for you to take a look when you get the chance (I’m in no hurry - I’ve got lots of other things to do in the meantime!) because I’m not even sure that what I’ve done so far is right and I’m a bit worried about messing things up...

**Comment by kingjr** [comment]
I won't have time to finish tonight, I'll work on it tomorrow..

**Comment by gmeade** [comment]
That’s fine! I can try to take another look too, but I feel like I’m going in circles and not getting anywhere...

**Comment by kingjr** [comment]
Ok 
- pull the repository: `git pull https://github.com/kingjr/meg_expectation_p3`
- have a look at what changed:https://github.com/kingjr/meg_expectation_p3/commits/master

What I did is the following:
In extract events, I call a hand-made function that extract all stim events (< 64), and look for the next two motor responses (> 64). I then combined their values (by adding them, which is possible because their are of different order of magnitude in base 2) and generated triplets of events (stim, motor1 and motor2). Finally, to differentiate the three events types in each triplets, I added 2 *\* 15 to the motor1 and 2 *\* 16 to the motor 2 triggers.

These combined events are then read and parsed by the get_events() function.

Check the code as much as possible and let me know if you understand it. 

Hope that helps!

**Comment by gmeade** [comment]
Definitely helps and I can almost follow ;-) The output is still incomprehensible to me, but I�m starting to get the general gist at least! And duh. I didn�t even think about defining events as all of the events and then only taking a subset of them. Cool.

A couple of things:

1) What are all the comments about the else�s in the conditions script (e.g., # is it an error? Else defined it�)? Just that they should be uppercase None, rather than lowercase?

2) I pushed a new version with an attempt at defining the local context condition. Hopefully I did it right? I can�t think of any other contrasts that we need, except maybe seen vs. unseen (defined as 1,2 vs. 3,4 and 1 vs. 2,3,4)� Do you think it is worth defining them now or just averaging across PASs later on?

3) I know that base 2s are important in CS, but I can�t figure out for the life of me how to transform the stimulus category into base 2s...

4) At the very least, I might as well start running all of the subjects through the filtering and ica steps since they are pretty much set and that will take quite some time, right? Are you thinking that we will do everything separately for each block and then average together at the end? Because right now, we�ve only been working with one block...

**Comment by kingjr** [comment]
1) You always need a else condition to check that you haven't missed some events definition.

2) Yes, you can always define more conditions if you think it's going to be useful at some point.

3) here's a hint ;)

```
import numpy as np
a = [1, 2, 5, 6, 9, 10, 13, 14, 17, 18, 21, 22, 25, 26,
     29, 30, 33, 34, 37, 38, 41, 42, 45, 46, 49, 50, 53,
     54, 57, 58]
b = [3, 4, 7, 8, 11, 12, 15, 16, 19, 20, 23, 24, 27,
     28, 31, 32, 35, 36, 39, 40, 43, 44, 47, 48, 51, 52,
     55, 56, 59, 60]

bin_a = [np.binary_repr(i, width=7) for i in a]
bin_b = [np.binary_repr(i, width=7) for i in b]

print([i[-2:] for i in bin_a])
print([i[-2:] for i in bin_b])
```

4) Yep

**Comment by kingjr** [comment]
If there isn't anything obvious, try summarizing the triggers as opposed to write every single one of them:
use 
`[i * 12 + j for i in range(5) for j in range(1,5)]`
instead of
`(range(1,5) + range(13,17) + range(25,29) + range(37,41) + range(49,53))`

**Comment by gmeade** [comment]
Hihi! Figured it out (I think!). I have pushed what, for me, is a complete conditions script. 

As a sanity check, I wanted to double-check the condition breakdown for our test subject against the behavioral results file, which had led to another serious problem… The extract_events file is only finding 228 events (it returns a file structure with 684 events = 228 *3), instead of the 312 that it should be finding. How do we access previous versions of the scripts to see if the problem is with the file (which I doubt, since it was working in FT), with the events that we are defining, or with the grouping by three process?

I am running everybody through the filtering and ica steps. The filtering seems to be fine, but I don’t know if my computer can handle the ica. It took hours for the full run of one subject and then my computer just became unresponsive near the end and it didn’t save the eeg file, so I have to run it again anyways. It did give me an error message (attached) - not sure if it is worth anything.

What else should I be doing to make the most out of our time together in a few days?!

**Comment by kingjr** [comment]
1. Mmmh, the discrepency is very large. Are you sure to go through all runs?
2. Decimate more the ica: see config.py
3. Can you run some first contrasts and show me the average across subjects? You can use this script: https://github.com/kingjr/meg_perceptual_decision_symbols/blob/master/scripts/run_mass_univariate.py

**Comment by gmeade** [comment]
1. No, the 228 vs. 312 is just for the first run (and 312 is what it should be because there are 1248 trials total), so it can’t be a run issue.
2. The ica_decim is 50 now; I will change it to 75 and see what happens.
3. But I have to run everyone through the first steps (through extract_epochs or evoked_contrast?) before I can do that, right?

**Comment by kingjr** [comment]
1. ok, how many events do you get < 64? Also, try to append run together.
2. Forget about the ica for now, we can run it on a big computer. Set apply_ica to False.
3. yep :)

**Comment by gmeade** [comment]
Right from the very beginning (i.e., the events that are defined in the extract_events function in conditions.py), it is only finding 228 events < 64…

**Comment by kingjr** [comment]
Ok, we need to think a bit then...

**Comment by gmeade** [comment]
What’s weird is that FT always found 312 events between 1 and 60 in this file, so it has to be something different about how we’re defining what counts as an event, rather than something about the file itself.

I did check in the right spot though, right? It is the call to mne.find_events that defines them and then you can check by doing print(sum(events[:,2]<64))?

**Comment by kingjr** [comment]
yes. Perhaps try different option in find_events (min duration, etc)? Do we know the number of trials per run?

**Comment by gmeade** [comment]
There were 312 trials per run, so Fieldtrip found all of them.

**Comment by kingjr** [comment]
Ok, try manual inspection:

```
raw = mne.io.Raw(fname, preload=True)
raw.pick_channels(['STI101'])
diff = raw._data[:, 1:] - raw._data[:, :-1]
print(sum(diff > 0))
print(sum(diff > 0) - sum(diff >= 64))
```

**Comment by gmeade** [comment]
I don’t really understand what I’m doing, but if I put that in the for loop in the run_extract_events file it gives me [0 0 0 …, 0 0 0] twice.

**Comment by kingjr** [comment]
This reads the STI101 channel on which we sent the TTL. This contains both stim and response triggers. By doing the difference you can roughly find the ttl onsets

**Comment by gmeade** [comment]
So it’s not supposed to give me 0s…

What’s weird is that if you ask it to tell you how many total events it extracted, it says 876. Of those 876, 228 are considered stim_inds and 648 are considered motor_inds. So we have more motor_inds than we’re supposed to and not nearly enough stim_inds.

**Comment by kingjr** [comment]
1. It's supposed to give you zeros if there isn't a ttl change at that time. Do np.where(diff>0)[0] to find where it changes.
2. Are we sure that the motor response are > 64? Can you gist the matlab script that identify the triggers?

**Comment by gmeade** [comment]
If I do print(len(np.where(diff>0)[0])), it gives me 960, which is probably right. 312 trials x 3 ttls per trigger = 936 plus the extra button presses at the beginning and to move on from feedback breaks.

I looked at the full list of events in MatLab a couple of days ago and I’m pretty sure that all of the motor responses are >= 64. The FT trial definition didn’t do anything with the motor triggers, it just looked for the triggers that were between 1 and 60 (i.e., the stim triggers) and it found 312 of those.

**Comment by kingjr** [comment]
Ok so it's probably due to the mne.find_events parameters

```
mne.find_events?
```

try play with them to get the right number

**Comment by gmeade** [comment]
Yeah, it is all starting to make sense. find_events is finding all of the motor responses (the 624 that we want plus the 24 extra ones that we now know we have from the total), but for some reason it is missing a bunch of the stim triggers. I already played a bit with the min_duration and it didn’t seem to help, but I will see what I can figure out.

**Comment by gmeade** [comment]
Problem solved! It was indeed the min_duration.

OK, next challenge: how and when do you usually append the different runs into one? Before doing anything?

**Comment by kingjr** [comment]
this should be automatic in run_extract_epochs.

Let's close this issue and move to another one

**Comment by gmeade** [comment]
Ah, so you were just saying to append the runs earlier to fix the trigger problem then?

**Comment by kingjr** [comment]
I don't think I understand what you mean.

Now that you have the right number of triggers (by correcting the parameter used in extract_events), you can run extract_events and extract_epochs on all runs (e.g. `runs = list(range(1, 11, 1))` in config)

**Comment by gmeade** [comment]
I am referring to your comment from earlier this morning: "ok, how many events do you get < 64? Also, try to append run together.” 

I thought you meant that I should add code in the beginning to append across all runs before doing anything, but I think that I misinterpreted and you only meant to try to append the runs together to fix the trigger problem?

**Comment by kingjr** [comment]
appending runs and finding all triggers are two distinct issues.

Now that you seem to find all stim event in the first run, let's move on to concatenating all runs together by changing the config parameters.

**Comment by gmeade** [comment]
Ah yeah, okay. I already did that last night - when I was running the run_filter and run_ica scripts, I ran them on all of the runs together. So good, I don’t need to change anything. I’m on my way out the door, but I will try to at least run everybody through the filtering step tonight and see if I can also get to the stage of plotting a couple of preliminary contrasts across subjects...

**Comment by kingjr** [comment]
You don't need to re-filter. The epoching is fast and directly read the filtered files.

**Comment by gmeade** [comment]
Wait, but I have to call run_filter in order to get a data structure that the other scripts can use, right? I can’t just start in the middle of the pipeline with the raw sss file (I have only ever run run_filter on this one subject that we’ve been working with), or can I?

**Comment by kingjr** [comment]
run_filter filters the raw data of each run and save them in a different file.
run_extract_events reads the filtered data and saves an event file for each run
run_extract_epochs reads the event files and the filtered data, and save an epoched data that concatenate all runs.

**Comment by gmeade** [comment]
Right. I was just confused when you said that I don’t need to re-filter. Maybe you thought that I had already done it across all subjects? But I still need to do that.

**Comment by kingjr** [comment]
yes, I thought you had. 

Focus on one subject for now, it's better to move fast on one subject than waiting.

**Comment by gmeade** [comment]
Okey dokey. Man, won’t it be great when we will be in the same room and we can just talk instead of going back and forth like this?! Alright, I really am leaving now...
