### ISSUE TITLE
FIX: run_extract_epochs

### ISSUE THREAD

**Issue by kingjr** [kingjr/meg_expectation_p3#5]
currently bugs

**Comment by kingjr** [comment]
@gmeade The reason why it bugs on my computer is because I don't have the raw files: `run_0X_sss_raw.fif` where X is 1-4.

Could you send these to me through dropbox?

**Comment by gmeade** [comment]
The filtered ones I’m guessing? I’m adding them to Dropbox so you should have them soon, and then let me know if that isn’t what you need… I don’t have any that are in the exact format as what you had below.

**Comment by kingjr** [comment]
non filtered

**Comment by gmeade** [comment]
Crap! So just the raw file (e.g., s4_sa130042_main1_sss.fif)?

**Comment by gmeade** [comment]
The only files I have with ‘raw’ in the file name are the filtered ones… And I thought that it was the original sss files that I had sent to you originally?

**Comment by kingjr** [comment]
ok, send whatever you have. You should have some non filtered data
somewhere though, shouldn't you?

**Comment by kingjr** [comment]
I don't have any crash on my computer. Can you output me the error on yours? You can push your contrasts, it shouldn't conflict.

**Comment by gmeade** [comment]
![screen shot 2015-05-17 at 18 17 11](https://cloud.githubusercontent.com/assets/11678885/7671151/ffb0006a-fcc0-11e4-9e4b-240da6c6e4bc.png)

**Comment by kingjr** [comment]
epochs_list seems empty. Can you try to find out why? What's in epochs if you debug? Can you show me the results/run_extract_epochs/*.log?

**Comment by gmeade** [comment]
Fixed it! On line 54, it calls the data file from the folder in the directory where it is, but I have my scripts on my computer and the data on the hard drive so there was no data file where it was looking. (I used to have the data_path in config defined as the hard drive, but we must have commented it out in order to run from your computer…).

How do I turn off the plots so that they just come up in the report but not one-by-one in separate windows?

**Comment by kingjr** [comment]
> How do I turn off the plots so that they just come up in the report but not one-by-one in separate windows?

They shouldn't pop up if you run the script `run scripts/run_extract_epochs.py`. Do they? You can set `open_browser = False` in `scripts/config.py` if you don't want the html report to open up once the script is finished.

**Comment by gmeade** [comment]
Yeah, they do. Ideally, I would like to have just the report, without each figure individually…??

**Comment by kingjr** [comment]
It may be due to a pylab issue. Try running ipython like this: `ipython --pylab qt`
