### ISSUE TITLE
events_params

### ISSUE THREAD

**Issue by gmeade** [kingjr/meg_expectation_p3#9]
I am trying to rerun everything for the subject that I have on my computer in order to test how I redefined the contrasts and I think there's a mistake in how we redefined the variables when we Skyped last?

In run_extract_events, we have (how do you make this look like real code?):

```
        if subject in events_params.keys():
            # r - 1 because run starts at 1 not 0
            events_param = events_params[subject][r - 1]
        else:
            events_param = dict()
```

But events_params, as defined in config is:

```
        events_params = [dict(name='stim_lock')]
```

I think that's a mistake, right? Because I don't see the relationship between the two (or understand why I didn't have this problem when I was running everybody before)?

**Comment by kingjr** [comment]
> I think that's a mistake, right?

Yes, you can remove this condition, this is only useful for buggy runs in specific subjects, which I don't think you have.

> (how do you make this look like real code?)

use the markdown: https://help.github.com/articles/github-flavored-markdown/
